apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: inoutlake/cinema-notification-service
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: email
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: notification-secret
              key: email_pass