apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
data:
  email: "bWFkZXVwY2luZW1hZW1haWxAbm9yZXBseWNpbmVtYS5jb20=" # base64 madeupcinemaemail@noreplycinema.com
  email_pass: "Y2luZW1hZW1haWxwYXNz" # base64 cinemaemailpass